export const GET_ARTICLES_LIST = "GET_ARTICLES_LIST";
export const GET_ARTICLES_LIST_ERROR = "GET_ARTICLES_LIST_ERROR";

export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";